// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVr9Jmbci-P6Di9a5Lv793fEPmzZiND10',
    appId: '1:601081233273:web:80a8fd413ed95b345479a8',
    messagingSenderId: '601081233273',
    projectId: 'flash2mart-customer-app',
    authDomain: 'flash2mart-customer-app.firebaseapp.com',
    storageBucket: 'flash2mart-customer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPEttaxrHW6kox1pFdMeS_CemkXVpY3qA',
    appId: '1:601081233273:android:5424b97f178dc3745479a8',
    messagingSenderId: '601081233273',
    projectId: 'flash2mart-customer-app',
    storageBucket: 'flash2mart-customer-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq4yxDSeYwNEJZ52QisKoG-qa6PEYmjZU',
    appId: '1:601081233273:ios:eb32fe6d77043ab15479a8',
    messagingSenderId: '601081233273',
    projectId: 'flash2mart-customer-app',
    storageBucket: 'flash2mart-customer-app.firebasestorage.app',
    iosBundleId: 'com.example.frontendCustomerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq4yxDSeYwNEJZ52QisKoG-qa6PEYmjZU',
    appId: '1:601081233273:ios:eb32fe6d77043ab15479a8',
    messagingSenderId: '601081233273',
    projectId: 'flash2mart-customer-app',
    storageBucket: 'flash2mart-customer-app.firebasestorage.app',
    iosBundleId: 'com.example.frontendCustomerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVr9Jmbci-P6Di9a5Lv793fEPmzZiND10',
    appId: '1:601081233273:web:51ddee61e939529a5479a8',
    messagingSenderId: '601081233273',
    projectId: 'flash2mart-customer-app',
    authDomain: 'flash2mart-customer-app.firebaseapp.com',
    storageBucket: 'flash2mart-customer-app.firebasestorage.app',
  );
}
